#docker-compose.yml
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./data:/data
      - ./static/images:/app/static/images
    environment:
      - DATABASE_URL=sqlite:////data/data.db
